[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{%- if version %}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else %}
## [Unreleased]
{%- endif %}
{% if breaking -%}
### Breaking
{% for commit in breaking -%}
- {{ commit.message | split(pat="\n") | first | upper_first | trim }}
{% endfor -%}
{%- endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits
    | filter(attribute="breaking", value=false) -%}
- {{ commit.message | split(pat="\n") | first | upper_first | trim }}
{% endfor %}
{%- endfor %}
"""
footer = """
{%- macro remote_url() -%}
  https://github.com/andrewesweet/spnego-proxy
{%- endmacro -%}
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
[{{ release.version | trim_start_matches(pat="v") }}]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
        {% else -%}
[{{ release.version | trim_start_matches(pat="v") }}]: {{ self::remote_url() }}/releases/tag/{{ release.version }}
        {% endif -%}
    {% else -%}
[unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
    {% endif -%}
{% endfor %}
"""
trim = true

[git]
tag_pattern = "v[0-9].*"
conventional_commits = true
filter_unconventional = true
breaking_always = true
commit_parsers = [
    { message = "^fix\\(security\\)", group = "Security" },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Changed" },
    { message = "^refactor", skip = true },
    { message = "^doc", skip = true },
    { message = "^test", skip = true },
    { message = "(?i)^ci", skip = true },
    { message = "^build", skip = true },
    { message = "^chore", skip = true },
    { message = "^Merge", skip = true },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"

[bump]
breaking_always_bump_major = true
features_always_bump_minor = true
